In [1]:
import pandas as pd

In [2]:
def factorial(n):
    if n==0 or n==1:
        return 1
    else:
        data = []
        data.append(1)
        data.append(1)
        for i in range(2,n+1):
            data.append(data[i-1] * i)
    return data[n]

In [3]:
def combinations(n, k):
    return factorial(n)/(factorial(k) * factorial(n-k))

In [4]:
def one_ticket_probability(numbers):
    possible_outcomes = combinations(49,6)
    number_of_successfull_outcomes = 1 # only one tuple of 6 numbers can win the lottery
    probab = number_of_successfull_outcomes/possible_outcomes
    percentg = probab * 100
    print("Your chances to win the big prize with {} are {:.7f}%".format(numbers, percentg))
    print("In other words, you have 1 in a {:,} chances to win".format(int(possible_outcomes)))

In [5]:
one_ticket_probability([1, 1, 1, 1, 1, 1])

Your chances to win the big prize with [1, 1, 1, 1, 1, 1] are 0.0000072%
In other words, you have 1 in a 13,983,816 chances to win

In [6]:
data = pd.read_csv('649.csv')
data.head(3)

,PRODUCT,DRAW NUMBER,SEQUENCE NUMBER,DRAW DATE,NUMBER DRAWN 1,NUMBER DRAWN 2,NUMBER DRAWN 3,NUMBER DRAWN 4,NUMBER DRAWN 5,NUMBER DRAWN 6,BONUS NUMBER
0,649,1,0,6/12/1982,3,11,12,14,41,43,13
1,649,2,0,6/19/1982,8,33,36,37,39,41,9
2,649,3,0,6/26/1982,1,6,23,24,27,39,34

In [7]:
data.tail(3)

,PRODUCT,DRAW NUMBER,SEQUENCE NUMBER,DRAW DATE,NUMBER DRAWN 1,NUMBER DRAWN 2,NUMBER DRAWN 3,NUMBER DRAWN 4,NUMBER DRAWN 5,NUMBER DRAWN 6,BONUS NUMBER
3662,649,3589,0,6/13/2018,6,22,24,31,32,34,16
3663,649,3590,0,6/16/2018,2,15,21,31,38,49,8
3664,649,3591,0,6/20/2018,14,24,31,35,37,48,17

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3665 entries, 0 to 3664
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PRODUCT          3665 non-null   int64
 1   DRAW NUMBER      3665 non-null   int64
 2   SEQUENCE NUMBER  3665 non-null   int64
 3   DRAW DATE        3665 non-null   object
 4   NUMBER DRAWN 1   3665 non-null   int64
 5   NUMBER DRAWN 2   3665 non-null   int64
 6   NUMBER DRAWN 3   3665 non-null   int64
 7   NUMBER DRAWN 4   3665 non-null   int64
 8   NUMBER DRAWN 5   3665 non-null   int64
 9   NUMBER DRAWN 6   3665 non-null   int64
 10  BONUS NUMBER     3665 non-null   int64
dtypes: int64(10), object(1)
memory usage: 315.1+ KB

In [9]:
def extract_numbers(row):
    return set(row[4:10].values)

In [10]:
winning_numbers = data.apply(extract_numbers, axis=1)
type(winning_numbers)

pandas.core.series.Series

In [11]:
def check_historical_occurence(user_input, winning_numbers):
    user_input = set(user_input)
    return (winning_numbers.values == user_input).sum()

In [12]:
check_historical_occurence([33, 5, 14, 47, 21, 31], winning_numbers)

0

In [13]:
def multi_ticket_probability(n_tickets):
    possible_outcomes = combinations(49, 6)
    successful_outcomes = n_tickets
    probab = successful_outcomes/possible_outcomes
    percentg = probab * 100
    print("Your chances to win the big prize  are {:.7f}%".format(percentg))
    print("In other words, you have {} in a {:,} chances to win".format(n_tickets, int(possible_outcomes)))

In [14]:
multi_ticket_probability(13983816)

Your chances to win the big prize  are 100.0000000%
In other words, you have 13983816 in a 13,983,816 chances to win

In [15]:
multi_ticket_probability(6991908)

Your chances to win the big prize  are 50.0000000%
In other words, you have 6991908 in a 13,983,816 chances to win

In [16]:
multi_ticket_probability(10)

Your chances to win the big prize  are 0.0000715%
In other words, you have 10 in a 13,983,816 chances to win

In [19]:
def probability_less_6(winning_numbers_expected):
    n_combinations_ticket = combinations(6, winning_numbers_expected)
    
    n_combinations_remaining = combinations(43, 6 - winning_numbers_expected)
    successful_outcomes = n_combinations_remaining * n_combinations_ticket
    
    total_possible_outcomes = combinations(49, 6)
    probab = successful_outcomes/total_possible_outcomes
    percentg = probab * 100
    print("Your chances to win a prize are {:.7f}%".format(percentg))
    print("In other words, you have {} in a {:,} chances to win".format(winning_numbers_expected, int(total_possible_outcomes)))

In [20]:
probability_less_6(2)

Your chances to win a prize are 13.2378029%
In other words, you have 2 in a 13,983,816 chances to win